create table public.users (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  auth_id uuid null,
  deleted_at timestamp with time zone null,
  constraint users_pkey primary key (id),
  constraint users_auth_id_fkey foreign key (auth_id) references auth.users (id)
);

create table public.contents (
  id bigint generated by default as identity not null,
  code character varying(100) not null,
  created_at timestamp with time zone not null default now(),
  type text not null,
  user_id bigint null,
  title text null,
  description text null,
  deleted_at timestamp with time zone null,
  start_at timestamp with time zone null,
  end_at timestamp with time zone null,
  constraint contents_pkey primary key (id),
  constraint contents_code_key unique (code),
  constraint contents_user_id_fkey foreign key (user_id) references public.users (id),
  constraint contents_type_check check (type = any (array['DRAW'::text, 'QUIZ'::text]))
);

create table public.invitation_codes (
  id bigserial not null,
  code character varying(100) not null,
  is_active boolean not null default true,
  expires_at timestamp with time zone null,
  last_used_at timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  name text null,
  content_id bigint not null,
  allowed_draw_count integer not null,
  used_draw_count integer not null default 0,
  constraint invitation_codes_pkey primary key (id),
  constraint invitation_codes_content_id_code_key unique (content_id, code),
  constraint invitation_codes_content_id_fkey foreign key (content_id) references public.contents (id),
  constraint invitation_codes_allowed_draw_count_check check (allowed_draw_count >= 0),
  constraint invitation_codes_used_draw_count_check check (used_draw_count >= 0),
  constraint invitation_codes_used_lte_allowed_check check (used_draw_count <= allowed_draw_count)
);

create table public.rewards (
  id bigserial not null,
  name character varying(200) not null,
  description text null,
  weight integer null,
  pool_count integer null,
  stock integer null,
  image character varying(500) null,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  allow_duplicate_reward boolean null default true,
  content_id bigint not null,
  deleted_at timestamp with time zone null,
  constraint rewards_pkey primary key (id),
  constraint rewards_content_id_fkey foreign key (content_id) references public.contents (id),
  constraint rewards_stock_check check (stock is null or stock >= 0),
  constraint rewards_weight_check check (weight is null or weight > 0),
  constraint rewards_pool_count_check check (pool_count is null or pool_count >= 0),
  constraint rewards_draw_mode_check check (
    (weight is not null and pool_count is null) or
    (weight is null and pool_count is not null)
  )
);

create table public.draw_results (
  id bigserial not null,
  invitation_code_id bigint not null,
  reward_id bigint not null,
  content_id bigint not null,
  draw_no integer not null,
  drawn_at timestamp with time zone not null default now(),
  delivered boolean not null default false,
  constraint draw_results_pkey primary key (id),
  constraint draw_results_invitation_code_id_draw_no_key unique (invitation_code_id, draw_no),
  constraint draw_results_content_id_fkey foreign key (content_id) references public.contents (id),
  constraint draw_results_invitation_code_id_fkey foreign key (invitation_code_id) references public.invitation_codes (id),
  constraint draw_results_reward_id_fkey foreign key (reward_id) references public.rewards (id),
  constraint draw_results_draw_no_check check (draw_no > 0)
);

create table public.inquiries (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  type character varying not null,
  title character varying not null,
  content character varying not null,
  status character varying not null default 'PENDING',
  user_id bigint null,
  constraint inquiry_pkey primary key (id),
  constraint inquiry_user_id_fkey foreign key (user_id) references public.users (id),
  constraint inquiries_type_check check (type = any (array['GENERAL'::character varying, 'BUG'::character varying, 'FEATURE'::character varying, 'ETC'::character varying])),
  constraint inquiries_status_check check (status = any (array['PENDING'::character varying, 'DONE'::character varying]))
);

create index if not exists idx_contents_code on public.contents using btree (code);
create index if not exists idx_contents_user_id on public.contents using btree (user_id);
create index if not exists idx_invitation_codes_content_id on public.invitation_codes using btree (content_id);
create index if not exists idx_rewards_content_id on public.rewards using btree (content_id);
create index if not exists idx_draw_results_content_id on public.draw_results using btree (content_id);
create index if not exists idx_draw_results_reward_id on public.draw_results using btree (reward_id);
