name: Deploy to cloudtype
on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'develop'
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: peppercode01/luckydrop
          stage: main
          yaml: |
            name: luckydrop-api-dev
            app: java@21
            options:
              ports: 8080
              env:
                - name: DB_PASSWORD
                  secret: DB_PASSWORD_DEV
                - name: DB_URL
                  secret: DB_URL_DEV
                - name: DB_USERNAME
                  secret: DB_USERNAME_DEV
                - name: SPRING_PROFILES_ACTIVE
                  value: develop
                - name: SUPABASE_ISSUER_URI
                  secret: SUPABASE_ISSUER_URI_DEV
                - name: SUPABASE_JWK_SET_URI
                  secret: SUPABASE_JWK_SET_URI_DEV
                - name: SUPABASE_JWT_AUDIENCE
                  value: authenticated
                - name: SUPABASE_SERVICE_ROLE_KEY
                  secret: SUPABASE_SERVICE_ROLE_KEY_DEV
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                branch: ${{ github.event.inputs.branch || 'develop' }}
              preset: java-springboot
